# Generated by Django 2.1.7 on 2019-03-27 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likecount',
            old_name='Liked_num',
            new_name='liked_num',
        ),
    ]
